/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedQaIndexRouteImport } from './routes/_authenticated/qa.index'
import { Route as AuthenticatedQaIdRouteImport } from './routes/_authenticated/qa.$id'
import { Route as AuthenticatedUpdatesIndexRouteImport } from './routes/_authenticated/updates.index'
import { Route as AuthenticatedUpdatesIdRouteImport } from './routes/_authenticated/updates.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQaIndexRoute = AuthenticatedQaIndexRouteImport.update({
  id: '/qa/',
  path: '/qa/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQaIdRoute = AuthenticatedQaIdRouteImport.update({
  id: '/qa/$id',
  path: '/qa/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpdatesIndexRoute =
  AuthenticatedUpdatesIndexRouteImport.update({
    id: '/updates/',
    path: '/updates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUpdatesIdRoute = AuthenticatedUpdatesIdRouteImport.update({
  id: '/updates/$id',
  path: '/updates/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ask': typeof AuthenticatedAskRoute
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/qa/$id': typeof AuthenticatedQaIdRoute
  '/updates/$id': typeof AuthenticatedUpdatesIdRoute
  '/qa/': typeof AuthenticatedQaIndexRoute
  '/updates/': typeof AuthenticatedUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ask': typeof AuthenticatedAskRoute
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/qa/$id': typeof AuthenticatedQaIdRoute
  '/updates/$id': typeof AuthenticatedUpdatesIdRoute
  '/qa': typeof AuthenticatedQaIndexRoute
  '/updates': typeof AuthenticatedUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/qa/$id': typeof AuthenticatedQaIdRoute
  '/_authenticated/updates/$id': typeof AuthenticatedUpdatesIdRoute
  '/_authenticated/qa/': typeof AuthenticatedQaIndexRoute
  '/_authenticated/updates/': typeof AuthenticatedUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ask'
    | '/home'
    | '/onboarding'
    | '/qa/$id'
    | '/updates/$id'
    | '/qa/'
    | '/updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ask'
    | '/home'
    | '/onboarding'
    | '/qa/$id'
    | '/updates/$id'
    | '/qa'
    | '/updates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ask'
    | '/_authenticated/home'
    | '/_authenticated/onboarding'
    | '/_authenticated/qa/$id'
    | '/_authenticated/updates/$id'
    | '/_authenticated/qa/'
    | '/_authenticated/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa/': {
      id: '/_authenticated/qa/'
      path: '/qa'
      fullPath: '/qa/'
      preLoaderRoute: typeof AuthenticatedQaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa/$id': {
      id: '/_authenticated/qa/$id'
      path: '/qa/$id'
      fullPath: '/qa/$id'
      preLoaderRoute: typeof AuthenticatedQaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/updates/': {
      id: '/_authenticated/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof AuthenticatedUpdatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/updates/$id': {
      id: '/_authenticated/updates/$id'
      path: '/updates/$id'
      fullPath: '/updates/$id'
      preLoaderRoute: typeof AuthenticatedUpdatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedQaIdRoute: typeof AuthenticatedQaIdRoute
  AuthenticatedUpdatesIdRoute: typeof AuthenticatedUpdatesIdRoute
  AuthenticatedQaIndexRoute: typeof AuthenticatedQaIndexRoute
  AuthenticatedUpdatesIndexRoute: typeof AuthenticatedUpdatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedQaIdRoute: AuthenticatedQaIdRoute,
  AuthenticatedUpdatesIdRoute: AuthenticatedUpdatesIdRoute,
  AuthenticatedQaIndexRoute: AuthenticatedQaIndexRoute,
  AuthenticatedUpdatesIndexRoute: AuthenticatedUpdatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
